# Site settings
title: Deep Frustration
smalltalk: "a discordant blog"
description: My journey from nothing to something in all things learning
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "https://github.com"
twitter_username: 
github_username: neale 
facebook_username: neale.ratzlaff
portfolio_url: 

# Build settings
markdown: kramdown
