# Site settings
title: Neale Ratzlaff
smalltalk: "Deep Learning, Hardware, and Other Hackings"
description: My journey from nothing to something in all things learning
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "https://github.com"
twitter_username: 
github_username: neale 
facebook_username: neale.ratzlaff
portfolio_url: 
gems: [jekyll-paginate]
# Build settings
markdown: kramdown
kramdown:
    input : GFM
    syntax_highlighter : rouge
#redcarpet:    
#    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
          
